### ISSUE TITLE
Improve README to indicate where build files are located

### ISSUE THREAD

**Issue by austinabell** [near/cargo-near#52]
A developer might be lost in-between the step of building/generating ABI and finding it in `<target>/near/...`. Might want to be clear about the assumptions or options for how it can be output.

**Comment by itegulov** [comment]
We are printing the resulting files' location after we successfully finish the command. So, @austinabell do you think this issue is still relevant? The problem is that there can be a few different places where the resulting files are going to end up at (always under `<target>/near` but the path can be longer if the current dir is not the workspace root for example). So hard to write specific instructions in the README without being too verbose.

**Comment by austinabell** [comment]
agree, this issue is no longer relevant!
